#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks=40
#SBATCH --ntasks-per-node=40
#SBATCH --threads-per-core=1
#SBATCH -A cli@cpu
#SBATCH -J Vcorr
#SBATCH -e zvcor.e%j
#SBATCH -o zvcor.o%j
#SBATCH --time=2:30:00
#SBATCH --exclusive

ulimit -s unlimited
CONFIG=eORCA12.L75
CASE=GJM2020

freq=1d
year1=1983
year2=2007

CONFCASE=${CONFIG}-${CASE}

MWDIR=$WORKDIR/${CONFIG}/${CONFCASE}-MEAN/
TOOLDIR=$DEVGIT/${CONFCASE}/TOOLS/V-correction

n=0
for y in $(seq $year1 $year2) ; do
cd $MWDIR/$freq/$y/
   for f in *_gridV.nc ; do
     $TOOLDIR/cdf_vcorr -f $f  &
     n=$(( n + 1 ))
     if [ $n = 39 ] ; then
       wait
       n=0
     fi
   done
done
wait

